### ISSUE TITLE
run make ,appears  "sys/_types.h: No such file or directory"

### ISSUE THREAD

**Issue by ericwang321** [timeisflowing/osmocom-bb#1]
ubuntu 16.04  64bit
after compile success arm-tool chain ,git clone .cd src directory,run make.appear 
> :/home/z00/osmocom-bb/src#make 
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --disable-tests, --disable-tests
cd shared/libosmocore/build-target && make
make[1]: Entering directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target'
make  all-recursive
make[2]: Entering directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target'
Making all in include
make[3]: Entering directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target/include'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target/include'
Making all in src
make[3]: Entering directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target/src'
make  all-am
make[4]: Entering directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target/src'
  CC       timer.lo
In file included from /home/z00/osmocom-bb/src/target/firmware/include/endian.h:5:0,
                 from /usr/include/x86_64-linux-gnu/sys/types.h:216,
                 from /home/z00/osmocom-bb/src/target/firmware/include/string.h:4,
                 from ../../src/timer.c:38:
/home/toor/osmocombb/install/arm-none-eabi/include/sys/_types.h:12:28: fatal error: machine/_types.h: No such file or directory
compilation terminated.
Makefile:488: recipe for target 'timer.lo' failed
make[4]: *** [timer.lo] Error 1
make[4]: Leaving directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target/src'
Makefile:366: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target/src'
Makefile:508: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target'
Makefile:380: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/z00/osmocom-bb/src/shared/libosmocore/build-target'
Makefile:34: recipe for target 'shared/libosmocore/build-target/src/.libs/libosmocore.a' failed
make: *** [shared/libosmocore/build-target/src/.libs/libosmocore.a] Error 2

**it seems canot find sys file ,but it exits. how to solve this problem ? 
thanks.**

**Comment by ericwang321** [comment]
after read the instruction carefully, I using clumsy method. it works. 
still  hope someone optimze the code in git. 

> 1.  export PATH
> mkdir /home/z00/, git clone osmocombb
> PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:**/home/toor/osmocombb/install/arm-none-eabi/include/machine/:/home/toor/osmocombb/install/bin"**
> 2. cp lib 
> cp -r /home/toor/osmocombb/install  home/z00/gnuarm/
> 
> 3.reinstall libosmocore ?,make clean 
> 
> 4. cd  /home/toor/osmocombb/src ,make 

done.

**Comment by timeisflowing** [comment]
(You need gnuarm installed ?) No need reinstall libosmocore, compiler not found library, make distclean or make clean; try make

**Comment by timeisflowing** [comment]
Added to current version, good fun :+1:
