### ISSUE TITLE
somthing is wrong when I install

### ISSUE THREAD

**Issue by alfiy** [timeisflowing/osmocom-bb#2]
./configure: line 3730: syntax error near unexpected token `LIBOSMOCORE,'
./configure: line 3730: `PKG_CHECK_MODULES(LIBOSMOCORE, libosmocore)'

**Comment by timeisflowing** [comment]
Not installed libosmocore, go https://osmocom.org/projects/libosmocore/wiki/Libosmocore and try again :)

**Comment by alfiy** [comment]
Hi,
thank you help me.
my libosmocore is "master af6710f [behind 15] fsm: fix apidoc of osmo_fsm_state_name()"

**Comment by timeisflowing** [comment]
Hi, 

Do you share a screenshot of what exactly caused the error?

**Comment by timeisflowing** [comment]
My libosmocore 

Master a66de71f8e8614cff7edc85fe979420716e5672c 

My edited Osmocom-BB 

Master 3b9a7f334092b7afc7a0d4a67eb92d495db3ebfc

You installed compiler of gnuarm toolchain ? 

https://osmocom.org/projects/baseband/wiki/GnuArmToolchain

**Comment by alfiy** [comment]
My toolchain
 GCC 4.8.2
Binutils 2.21.1
Newlib 1.19

I reinstall libosmocore
My libosmocore 
Master 0145751a97c5caad57eb6c0b4a60a1736dee371f

Osmocom-bb 
git clone https://github.com/timeisflowing/osmocom-bb.git
Master 118d65f2d0097ea36cd30ab9aaf62ef0c7ad1694

the error is still same

**Comment by timeisflowing** [comment]
step 1 https://prnt.sc/lwzxyj
step 2 https://prnt.sc/lwzycf

No problem with me, man sorry :(

**Comment by alfiy** [comment]
找到原因了，还是libosmocore导致的，我重新编译了Master a66de71f8e8614cff7edc85fe979420716e5672c分支成功了。谢谢你的帮助，不知有没有其他的联系方式。我邮箱及QQ 13012648@qq.com

**Comment by timeisflowing** [comment]
Solution solved by re-installing libosmocore, thanks
